title: "Harold Montecinos"
description: "Backend Developer | Java Specialist"
url: "https://harold-20-06.github.io"
theme: jekyll-theme-minimal

avatar: "https://avatars.githubusercontent.com/u/32402240?v=4"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"