title: Harold Montecinos  
description: Backend Developer Java | Spring Boot | APIs REST  
baseurl: ""  
url: "https://haroldmontecinos.github.io"  

# Redes sociales
social:
  github: github.com/harold-20-06
  linkedin: linkedin.com/in/harold-montecinos
  #twitter: tu-twitter    # Opcional

# Configuración técnica
plugins:
  - jekyll-feed