#
# Configuración personalizada para tu sitio Jekyll
#

# Nombre y descripción
name: Harold Mike Montecinos Mujiano
description: Software Backend Developer | Java Specialist

# Avatar (reemplaza con tu foto de perfil)
avatar: https://avatars.githubusercontent.com/u/32402240?v=4&size=64

# Información de contacto y redes
footer-links:
  email: haroldmontecinos2002@gmail.com
  github: harold-20-06
  linkedin: https://www.linkedin.com/in/harold-montecinos/
  # Opcionales (elimina los que no uses):
  # twitter: tu-usuario
  # stackoverflow: users/tu-id

# Configuración técnica (no modificar si no es necesario)
url: https://harold-20-06.github.io
baseurl: ""  # Déjalo vacío si es tu repositorio principal (username.github.io)

# Jekyll settings
permalink: /:title/
version: v1.2.0

# Markdown y sintaxis
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins esenciales
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Excluir archivos innecesarios
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md